#pragma once

#include <algorithm>
#include <any>
#include <array>
#include <atomic>
#include <bit>
#include <concepts>
#include <charconv>
#include <cassert>
#include <cctype>
#include <cfloat>
#include <cmath>
#include <csetjmp>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <deque>
#include <filesystem>
#include <format>
#include <fstream>
#include <functional>
#include <iterator>
#include <initializer_list>
#include <locale>
#include <map>
#include <memory>
#include <mutex>
#include <numeric>
#include <queue>
#include <ranges>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <variant>
#include <vector>
#include <xxh64.h>
#include "MiscHelpers.h"
#include "StrUtils.h"
#include "IOUtils.h"
// #include "PlatformService.h"