name: "Zip release artifact"
description: "Download and zip release artifact"

inputs:
  github_token:
    description: "GitHub API token."
    required: true
    type: string
  artifact_name:
    description: "Name of the input artifact to download."
    required: true
    type: string
  release_name:
    description: "Name of the release zip file (without extension)."
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download mupen-release-stable-windows-x86 artifact from latest run on current branch
      uses: dawidd6/action-download-artifact@v21
      with:
        github_token: ${{ inputs.github_token }}
        workflow: build.yml
        branch: ${{ github.ref_name }}
        name: ${{ inputs.artifact_name }}
        path: ./${{ inputs.release_name }}

    - name: Zip release artifacts
      shell: sh
      run: |
        zip -r ${{ inputs.release_name }}.zip ./${{ inputs.release_name }}/