//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch res.rc
//
#define IDD_RSPCONFIG 100
#define IDC_ALISTS_INSIDE_RSP 101
#define IDC_ALISTS_EMU_DEFINED_PLUGIN 102
#define IDC_ALISTS_RSP_DEFINED_PLUGIN 103
#define IDC_METHOD 104
#define IDC_EDIT_AUDIO_PLUGIN 106
#define IDC_BROWSE_AUDIO_PLUGIN 107
#define IDC_UCODE_CACHE_VERIFY 108
