name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

jobs:
  build-debug-nightly:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - arch: x86
            zig_target: x86-windows
            vcpkg_triplet: x86-zig-windows-dynamic
          - arch: x64
            zig_target: x86_64-windows
            vcpkg_triplet: x64-zig-windows-dynamic

    steps:
      - uses: actions/checkout@v6

      - name: Install MinGW-w64
        run: |
          sudo apt-get update
          sudo apt-get install --yes mingw-w64

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Set VERSION_SUFFIX and NIGHTLY
        run: |
          echo "NIGHTLY=1" >> "$GITHUB_ENV"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION_SUFFIX=" >> "$GITHUB_ENV"
          else
            echo "VERSION_SUFFIX=-nightly-${GITHUB_SHA::7}" >> "$GITHUB_ENV"
          fi

      - name: Create vcpkg cache directory
        run: mkdir -p "$VCPKG_DEFAULT_BINARY_CACHE"

      - name: Cache vcpkg binaries and installed packages
        uses: actions/cache@v5
        with:
          path: |
            vcpkg_cache
            build/vcpkg_installed
          key: >
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{
            hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-

      - name: Install dependencies
        run: zig build vcpkg -p build -Dtarget=${{ matrix.zig_target }}

      - name: Build
        run: zig build -p build -Dtarget=${{ matrix.zig_target }} -Dvcpkg_installed=build/vcpkg_installed/${{ matrix.vcpkg_triplet }}

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: mupen-debug-nightly
          path: build/out
          retention-days: 14

  build-release-nightly:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - arch: x86
            zig_target: x86-windows
            vcpkg_triplet: x86-zig-windows-dynamic
          - arch: x64
            zig_target: x86_64-windows
            vcpkg_triplet: x64-zig-windows-dynamic

    steps:
      - uses: actions/checkout@v6

      - name: Install MinGW-w64
        run: |
          sudo apt-get update
          sudo apt-get install --yes mingw-w64

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Set VERSION_SUFFIX and NIGHTLY
        run: |
          echo "NIGHTLY=1" >> "$GITHUB_ENV"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION_SUFFIX=" >> "$GITHUB_ENV"
          else
            echo "VERSION_SUFFIX=-nightly-${GITHUB_SHA::7}" >> "$GITHUB_ENV"
          fi

      - name: Create vcpkg cache directory
        run: mkdir -p "$VCPKG_DEFAULT_BINARY_CACHE"

      - name: Cache vcpkg binaries and installed packages
        uses: actions/cache@v5
        with:
          path: |
            vcpkg_cache
            build/vcpkg_installed
          key: >
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{
            hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-

      - name: Install dependencies
        run: zig build vcpkg -p build -Dtarget=${{ matrix.zig_target }}

      - name: Build
        run: zig build -p build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.zig_target }} -Dvcpkg_installed=build/vcpkg_installed/${{ matrix.vcpkg_triplet }}

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: mupen-release-nightly
          path: build/out
          retention-days: 14

  build-release-stable:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - arch: x86
            zig_target: x86-windows
            vcpkg_triplet: x86-zig-windows-dynamic
          - arch: x64
            zig_target: x86_64-windows
            vcpkg_triplet: x64-zig-windows-dynamic

    steps:
      - uses: actions/checkout@v6

      - name: Install MinGW-w64
        run: |
          sudo apt-get update
          sudo apt-get install --yes mingw-w64

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Create vcpkg cache directory
        run: mkdir -p "$VCPKG_DEFAULT_BINARY_CACHE"

      - name: Cache vcpkg binaries and installed packages
        uses: actions/cache@v5
        with:
          path: |
            vcpkg_cache
            build/vcpkg_installed
          key: >
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{
            hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-

      - name: Install dependencies
        run: zig build vcpkg -p build -Dtarget=${{ matrix.zig_target }}

      - name: Build
        run: zig build -p build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.zig_target }} -Dvcpkg_installed=build/vcpkg_installed/${{ matrix.vcpkg_triplet }}

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: mupen-release-stable
          path: build/out
          retention-days: 14
