name: Check format

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  clang-format:
    name: clang-format (C/C++)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "./src"
          exclude: "./lib ./tools"
          extensions: "c,cpp,h,hpp"
          clangFormatVersion: 20
          style: file
