name: Check format

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-format:
    name: check all formatting
    runs-on: ubuntu-latest-slim

    steps:
      - uses: actions/checkout@v6
      - parallel:
        - name: check against clang-format
          uses: DoozyX/clang-format-lint-action@v0.20
          with:
            source: "./src"
            exclude: "./lib ./tools"
            extensions: "c,cpp,h,hpp"
            clangFormatVersion: 20
            style: file
        - name: check copyright headers
          shell: bash
          working-directory: ${{ env.GITHUB_WORKSPACE }}
          run: |
            shopt -s globstar nullglob
            python3 tools/check_headers.py \
              src/**/*{.c,.h,.cpp,.hpp} \
              src/**/*.rc \
              src/**/*.qml \
              src/**/CMakeLists.txt src/**/*.cmake \
              src/**/*.lua \
              tools/**/*.py
