name: Generate release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.2.0)"
        required: true
        type: string

jobs:
  build-stable:
    name: Build stable release artifacts
    uses: $/.github/workflows/build-stable.yml
  
  draft-release:
    name: Setup draft release
    runs-on: ubuntu-latest
    needs: build-stable
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff

      - name: Get latest commit hash
        run: echo "short_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        
      - parallel:
        - name: Download and zip x86 release
          uses: ./.github/actions/zip-release
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            artifact_name: mupen-release-stable-windows-x86
            release_name: mupen-windows-x86
        - name: Download and zip x64 release
          uses: ./.github/actions/zip-release
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            artifact_name: mupen-release-stable-windows-x86
            release_name: mupen-windows-x64

      - name: Generate changelog with git-cliff
        id: changelog
        run: |
          git cliff --unreleased --config cliff.toml --output CHANGELOG_DRAFT.md
          {
            echo 'body<<EOF'
            cat CHANGELOG_DRAFT.md
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Create draft stable release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          prerelease: false
          draft: true
          files: |
            mupen64-w32
            mupen64-w64
