name: Call org release notifier

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify:
    uses: mupen64/.github/.github/workflows/notify-release.yml@main
    secrets: inherit
